### ISSUE TITLE
Management: adding a category doesn't work

### ISSUE THREAD

**Issue by ulbricht-inr** [hftlclub/node-iltis#33] opened 2017-10-15 13:17 UTC
after typing name, klick add.. nothing added to the list ....no errors, but green acknowledgement
but it appears in the filter of the product table....
and you can add products to it...
than it appears in the category-table.....
confusing....

**Comment by fmalcher** [comment] 2017-10-16 07:52
Possible duplicate of https://github.com/hftlclub/node-iltis/issues/28
The category is being created but as long as there are no products in it, it's not being displayed in the list.

**Closed as completed by fmalcher** 2017-10-16 07:52 UTC
Labels: duplicate
